import { tenantsArrayField as tenantsArrayFieldPlugin } from '@payloadcms/plugin-multi-tenant/fields';
import type { Field } from 'payload';

import { systemUserOrTenantAdminAccess } from '@codeware/app-cms/util/access';
import { enumName } from '@codeware/app-cms/util/db';

/**
 * Customized tenants array field in the users collection, based on the `tenantsArrayField` plugin utility function.
 * The reason for a customized field is to adapt the field in a way that the plugin does not support.
 *
 * Using this field requires `tenantsArrayField.includeDefaultField` to be set to `false` in the plugin configuration.
 */
export const tenantsArrayField = (): Field => {
  const tenantsArrayField = tenantsArrayFieldPlugin({
    // Add a role field to complement the tenant field
    rowFields: [
      {
        name: 'role',
        type: 'select',
        label: { en: 'Role', sv: 'Roll' },
        enumName: enumName('tenant_user_role'),
        options: [
          { label: { en: 'User', sv: 'Användare' }, value: 'user' },
          { label: { en: 'Admin', sv: 'Administratör' }, value: 'admin' }
        ],
        admin: {
          description: {
            en: 'Admins have access to manage the users in the workspace.',
            sv: 'Administratörer har behörighet att hantera användare i arbetsytan.'
          }
        },
        required: true,
        defaultValue: 'user'
      }
    ]
  });

  // Get the tenant field generated by the plugin and customize it
  const tenantField = tenantsArrayField.fields[0];
  if (
    tenantField.type === 'relationship' &&
    tenantField.relationTo === 'tenants'
  ) {
    tenantField.label = { en: 'Workspace', sv: 'Arbetsyta' };
  } else {
    console.warn(
      'Expected the first field in the tenants array field to be the tenant field generated by the plugin'
    );
  }

  return {
    ...tenantsArrayField,
    interfaceName: 'TenantsArrayField',
    labels: {
      singular: { en: 'Workspace', sv: 'Arbetsyta' },
      plural: { en: 'Workspaces', sv: 'Arbetsytor' }
    },
    access: {
      create: systemUserOrTenantAdminAccess,
      update: systemUserOrTenantAdminAccess
    },
    admin: {
      ...(tenantsArrayField.admin ?? {}),
      description: {
        en: 'Users can be restricted to one or many workspaces.',
        sv: 'Användare kan begränsas till en eller flera arbetsytor.'
      },
      components: {
        // Hide the top level label since we have a similar label in the tab
        Label: undefined,
        // Custom tenant/role header
        RowLabel: '@codeware/apps/cms/components/TenantsArrayRowLabel'
      },
      initCollapsed: true
    }
  };
};
