import * as core from '@actions/core';
import * as github from '@actions/github';
import { withGitHub } from '@codeware/shared/util/github';

import { getFeatureBranchName } from './get-feature-branch-name';
import type { DeferredPrompt, MigrateConfig, VersionInfo } from './types';

export const createPullRequest = async (
  config: MigrateConfig,
  versionInfo: Pick<VersionInfo, 'currentVersion' | 'latestVersion'>,
  status: {
    testsPass?: boolean;
    e2ePass?: boolean;
    deferredPrompts?: Array<DeferredPrompt>;
  }
): Promise<number> => {
  const { mainBranch, skipE2E, skipTests, token } = config;
  const octokit = github.getOctokit(token);

  const { currentVersion, latestVersion } = versionInfo;
  const { deferredPrompts = [], e2ePass, testsPass } = status;

  const branchName = getFeatureBranchName(latestVersion);

  const prTitle = `Update @nx/workspace to ${latestVersion}`;
  const prBody = [`Update Nx from ${currentVersion} to ${latestVersion}`, ''];
  if (!skipTests) {
    prBody.push(testsPass ? '✅ Tests passed' : '⚠️ Tests failed', '');
  }
  if (!skipE2E) {
    prBody.push(e2ePass ? '✅ E2E tests passed' : '⚠️ E2E tests failed', '');
  }
  if (deferredPrompts.length) {
    prBody.push(
      `⚠️ ${deferredPrompts.length} prompt migration(s) were not applied`,
      '',
      'Nx defers prompt migrations to an interactive AI agent, which is not available in CI.',
      'The prompt files are committed to this branch, apply them locally in the listed order:',
      '',
      ...deferredPrompts.map(({ name, prompt }) => `- \`${prompt}\` (${name})`),
      ''
    );
  }
  prBody.push(
    '',
    '> Auto-generated by [@cdwr/nx-migrate-action][1]',
    '',
    '[1]: https://github.com/codeware-sthlm/cdwr/tree/main/packages/nx-migrate-action'
  );

  // Create a new pull request
  const {
    data: { number }
  } = await withGitHub(() =>
    octokit.rest.pulls.create({
      ...github.context.repo,
      title: prTitle,
      body: prBody.join('\n'),
      head: branchName,
      base: mainBranch,
      draft: false
    })
  );

  core.info(`Created pull request #${number}`);

  return number;
};
