import type { Tenant } from '@codeware/shared/util/payload-types';
import type { Payload, TypedLocale } from 'payload';

export type TenantData = Pick<
  Tenant,
  'name' | 'description' | 'apiKey' | 'slug' | 'supportedLocales'
> & { slug: string }; // Ensure slug is required for tenant lookup and creation

/**
 * Ensure that a tenant exists and has an API key created.
 *
 * When the API key is not provided, it will be generated by Payload.
 *
 * @param payload - Payload instance
 * @param data - Tenant data
 * @param options - Seed options
 * @returns The created tenant or the id if the tenant exists
 */
export async function ensureTenant(
  payload: Payload,
  data: TenantData,
  options: { locale: TypedLocale; transactionID: string | number | undefined }
): Promise<Tenant | number> {
  const { locale, transactionID } = options;
  const { apiKey, description, name, slug, supportedLocales } = data;

  // Check if the tenant exists with the given slug
  const tenants = await payload.find({
    collection: 'tenants',
    where: { slug: { equals: slug } },
    pagination: false,
    req: { transactionID }
  });

  if (tenants.totalDocs > 1) {
    throw new Error(`Multiple tenants found with slug '${slug}', skip`);
  }

  if (tenants.totalDocs === 1) {
    return tenants.docs[0].id;
  }

  // No tenant found, create one

  const tenant = await payload.create({
    collection: 'tenants',
    data: {
      enableAPIKey: true,
      apiKey,
      description,
      name,
      slug,
      supportedLocales
    },
    locale,
    req: { transactionID }
  });

  return tenant;
}
