/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Users can be restricted to one or many workspaces.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TenantsArrayField".
 */
export type TenantsArrayField =
  | {
      tenant: number | Tenant;
      /**
       * Admins have access to manage the users in the workspace.
       */
      role: 'user' | 'admin';
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavigationArrayItems".
 */
export type NavigationArrayItems =
  | {
      reference:
        | {
            relationTo: 'pages';
            value: number | Page;
          }
        | {
            relationTo: 'posts';
            value: number | Post;
          };
      labelSource?: ('document' | 'custom') | null;
      customLabel?: string | null;
      id?: string | null;
    }[]
  | null;
/**
 * The day-by-day agenda. Add one entry per day of the tour, in order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TourItinerary".
 */
export type TourItinerary =
  | {
      /**
       * What happens this day, e.g. "Arrival & welcome dinner".
       */
      title: string;
      /**
       * Wineries, hotels and stops for this day.
       */
      places?: (number | Place)[] | null;
      /**
       * Plain text; line breaks are preserved.
       */
      description?: string | null;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    tenants: TenantAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {
    about: AboutBlock;
    callout: CalloutBlock;
    card: CardBlock;
    code: CodeBlock;
    content: ContentBlock;
    'feature-cards': FeatureCardsBlock;
    'file-area': FileAreaBlock;
    form: FormBlock;
    hero: HeroBlock;
    image: ImageBlock;
    media: MediaBlock;
    'pill-list': PillListBlock;
    posts: PostsBlock;
    'reusable-content': ReusableContentBlock;
    showcase: ShowcaseBlock;
    'social-media': SocialMediaBlock;
    spacing: SpacingBlock;
    tours: ToursBlock;
    video: VideoBlock;
  };
  collections: {
    categories: Category;
    faq: Faq;
    media: Media;
    navigation: Navigation;
    pages: Page;
    places: Place;
    'platform-labels': PlatformLabel;
    posts: Post;
    'reusable-content': ReusableContent;
    'site-settings': SiteSetting;
    'stock-media': StockMedia;
    tags: Tag;
    tenants: Tenant;
    'tour-signups': TourSignup;
    tours: Tour;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      'relations.relatedPosts': 'posts';
    };
    tags: {
      'relations.relatedMedia': 'media';
    };
    tenants: {
      'relations.relatedUsers': 'users';
      'relations.relatedPages': 'pages';
      'relations.relatedPosts': 'posts';
      'relations.relatedCategories': 'categories';
      'relations.relatedMedia': 'media';
    };
  };
  collectionsSelect: {
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    'platform-labels': PlatformLabelsSelect<false> | PlatformLabelsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'reusable-content':
      | ReusableContentSelect<false>
      | ReusableContentSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'stock-media': StockMediaSelect<false> | StockMediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'tour-signups': TourSignupsSelect<false> | TourSignupsSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions':
      | FormSubmissionsSelect<false>
      | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    'payload-preferences':
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    'payload-migrations':
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'sv')
    | ('en' | 'sv')[];
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats':
      | PayloadJobsStatsSelect<false>
      | PayloadJobsStatsSelect<true>;
  };
  locale: 'en' | 'sv';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Tenant | User;
  jobs: {
    tasks: {
      'anonymize-tour-signups': TaskAnonymizeTourSignups;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface TenantAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  /**
   * Optional heading shown above the deployment details.
   */
  heading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  showMark?: boolean | null;
  heading: string;
  body?: string | null;
  link: CalloutLink;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutLink".
 */
export interface CalloutLink {
  type?: ('reference' | 'custom') | null;
  newTab?: boolean | null;
  reference?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  /**
   * Add protocol (http:// or https://) if the link is external
   */
  url?: string | null;
  label: string;
}
/**
 * Pages are the foundation of the system and are used to build your website. Work with drafts and publish when ready.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * The name of the page used for navigation links.
   */
  name: string;
  /**
   * A pre-designed header on top of the page. Provide for a consistent look and feel or customize everything in layout builder.
   */
  header?: string | null;
  /**
   * Build your page by adding the content you need. E.g. choose "Content" to create one or more columns. Then use the text editor and add more blocks if needed in each column.
   */
  layout: (
    | AboutBlock
    | CalloutBlock
    | CardBlock
    | CodeBlock
    | ContentBlock
    | FeatureCardsBlock
    | FileAreaBlock
    | FormBlock
    | HeroBlock
    | ImageBlock
    | MediaBlock
    | PillListBlock
    | PostsBlock
    | ReusableContentBlock
    | ShowcaseBlock
    | SocialMediaBlock
    | SpacingBlock
    | ToursBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Used for url paths. Will be automatically generated from name if left empty.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * A workspace is like an organization or group of users and is often called a "tenant". You must be a member to see its content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  iconConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  name: string;
  description?: string | null;
  /**
   * Select the locales your web client should support. Multiple locales will enable the language selector in the admin UI.
   */
  supportedLocales: ('en' | 'sv')[];
  /**
   * Domains this workspace is reachable on, in addition to its .fly.dev address — which keeps working and stays useful for support. Add the domain here first, then create the DNS records shown after saving.
   */
  domains?:
    | {
        /**
         * The domain on its own — no https://, no path.
         */
        hostname: string;
        /**
         * The Fly app that serves this domain. The certificate is attached to it.
         */
        app: string;
        /**
         * The address the app presents as its own, in links and emails. One per app.
         */
        isPrimary?: boolean | null;
        certificate?: {
          isConfigured?: boolean | null;
          isApex?: boolean | null;
          status?: string | null;
          checkedAt?: string | null;
          dnsValidationHostname?: string | null;
          dnsValidationTarget?: string | null;
          dnsValidationInstructions?: string | null;
          rateLimitedUntil?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  relations?: {
    relatedUsers?: {
      docs?: (number | User)[];
      hasNextPage?: boolean;
      totalDocs?: number;
    };
    relatedPages?: {
      docs?: (number | Page)[];
      hasNextPage?: boolean;
      totalDocs?: number;
    };
    relatedPosts?: {
      docs?: (number | Post)[];
      hasNextPage?: boolean;
      totalDocs?: number;
    };
    relatedCategories?: {
      docs?: (number | Category)[];
      hasNextPage?: boolean;
      totalDocs?: number;
    };
    relatedMedia?: {
      docs?: (number | Media)[];
      hasNextPage?: boolean;
      totalDocs?: number;
    };
  };
  /**
   * Used for url paths. Will be automatically generated from name if left empty.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'tenants';
}
/**
 * Manage users and their access to workspaces.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * System users have access to manage the whole system and do not need to be members of a workspace. For normal users, it is a requirement to be members of a workspace.
   */
  role: 'user' | 'system-user';
  tenants?: TenantsArrayField;
  /**
   * Short description of the user.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Posts are standalone pages such as articles or blog posts. Work with drafts and publish when ready.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * The title of the post and name used in navigation.
   */
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * The authors of the post.
   */
  authors?: (number | User)[] | null;
  /**
   * Used for url paths. Will be automatically generated from title if left empty.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Upload media files to the system and use them on your website. Images are converted to webp format for better performance.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  filenameWithoutPrefix?: string | null;
  /**
   * Alternative text for SEO and accessibility.
   */
  alt: string;
  /**
   * Caption to display below an image or video.
   */
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?: (number | Tag)[] | null;
  prefix?: string | null;
  /**
   * Allow external access to the file without authentication. For example, this is required for file areas and document images.
   */
  external?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    meta?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Labels are used to organize photos and files so they are easy to find and select.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * Select an icon and color that represent the tag.
   */
  brand?: {
    icon?: string | null;
    color?: string | null;
  };
  relations?: {
    relatedMedia?: {
      docs?: (number | Media)[];
      hasNextPage?: boolean;
      totalDocs?: number;
    };
  };
  /**
   * Used for url paths. Will be automatically generated from name if left empty.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Categories makes it possible to group blog posts by topic for better overview.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * The name of the category.
   */
  name: string;
  relations?: {
    relatedPosts?: {
      docs?: (number | Post)[];
      hasNextPage?: boolean;
      totalDocs?: number;
    };
  };
  /**
   * Used for url paths. Will be automatically generated from name if left empty.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBlock".
 */
export interface CardBlock {
  cards?:
    | {
        /**
         * Select an icon and color that represent the card
         */
        brand?: {
          icon?: string | null;
          color?: string | null;
        };
        title: string;
        /**
         * A text that will complement the title
         */
        description?: string | null;
        content: string;
        /**
         * Let the card link to a page or external URL
         */
        enableLink?: boolean | null;
        link?: CardBlockLink;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBlockLink".
 */
export interface CardBlockLink {
  type?: ('reference' | 'custom') | null;
  newTab?: boolean | null;
  reference?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  /**
   * Add protocol (http:// or https://) if the link is external
   */
  url?: string | null;
  navTrigger?: ('card' | 'link') | null;
  label?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language: 'ts' | 'plaintext' | 'tsx' | 'js' | 'jsx';
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('one-third' | 'half' | 'two-thirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format:
              | 'left'
              | 'start'
              | 'center'
              | 'right'
              | 'end'
              | 'justify'
              | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        blocks?:
          | (
              | CardBlock
              | CodeBlock
              | FormBlock
              | ImageBlock
              | MediaBlock
              | ReusableContentBlock
              | SocialMediaBlock
              | SpacingBlock
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
/**
 * Build contact and signup forms to place on your pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            /**
             * Set number of columns the field should span (defaults to 6 = full width).
             */
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            /**
             * Set number of columns the field should span (defaults to 6 = full width).
             */
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            /**
             * Set number of columns the field should span (defaults to 6 = full width).
             */
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format:
                  | 'left'
                  | 'start'
                  | 'center'
                  | 'right'
                  | 'end'
                  | 'justify'
                  | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            /**
             * Set number of columns the field should span (defaults to 6 = full width).
             */
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            /**
             * Lowest value a visitor may enter. Leave empty for no limit.
             */
            min?: number | null;
            /**
             * Highest value a visitor may enter. Leave empty for no limit.
             */
            max?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            /**
             * Set number of columns the field should span (defaults to 6 = full width).
             */
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            /**
             * Set number of columns the field should span (defaults to 6 = full width).
             */
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            /**
             * Set number of columns the field should span (defaults to 6 = full width).
             */
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'date';
          }
        | {
            name: string;
            label?: string | null;
            /**
             * Set number of columns the field should span (defaults to 6 = full width).
             */
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'radio';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format:
              | 'left'
              | 'start'
              | 'center'
              | 'right'
              | 'end'
              | 'justify'
              | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  /**
   * Select an image.
   */
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'media';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReusableContentBlock".
 */
export interface ReusableContentBlock {
  reusableContent: number | ReusableContent;
  /**
   * Optional reference that can be used to identify this block with CSS or JavaScript.
   */
  refId?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'reusable-content';
}
/**
 * Reusable content is created so that the same content can be reused in multiple places in pages and posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-content".
 */
export interface ReusableContent {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * What is the reusable content about? This is just an internal help text to keep the content organized.
   */
  title: string;
  layout: (
    | CardBlock
    | CodeBlock
    | ContentBlock
    | FileAreaBlock
    | FormBlock
    | ImageBlock
    | MediaBlock
    | SocialMediaBlock
    | SpacingBlock
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FileAreaBlock".
 */
export interface FileAreaBlock {
  /**
   * Select tags that represent the files to show in the file area.
   */
  tags?: (number | Tag)[] | null;
  files?:
    | {
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'file-area';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialMediaBlock".
 */
export interface SocialMediaBlock {
  social?:
    | {
        platform:
          | 'discord'
          | 'email'
          | 'facebook'
          | 'github'
          | 'instagram'
          | 'linkedin'
          | 'npm'
          | 'phone'
          | 'web'
          | 'x'
          | 'youtube';
        email?: string | null;
        phone?: string | null;
        url?: string | null;
        withLabel?: boolean | null;
        /**
         * Short text to display next to the icon
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * How the social media links are displayed
   */
  direction?: ('horizontal' | 'vertical') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'social-media';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacingBlock".
 */
export interface SpacingBlock {
  /**
   * Regular spacing size matches the default spacing between blocks
   */
  size: 'tight' | 'regular' | 'loose';
  divider?: boolean | null;
  /**
   * Override divider theme color
   */
  color?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardsBlock".
 */
export interface FeatureCardsBlock {
  /**
   * Small uppercase label shown above the heading
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Short paragraph below the heading
   */
  intro?: string | null;
  /**
   * Desktop column count. Auto fits to the number of items.
   */
  columns?: ('auto' | '2' | '3' | '4') | null;
  items?:
    | {
        /**
         * Icon and color for this item
         */
        brand?: {
          icon?: string | null;
          color?: string | null;
        };
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'feature-cards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Optional pill above the headline. The tenant logo is shown automatically when available.
   */
  badge?: string | null;
  heading: string;
  /**
   * The part that hooks the reader and conveys the most essential information (often answering who, what, when, where, why).
   */
  lede: string;
  actions?:
    | {
        link: HeroActionLink;
        emphasis?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroActionLink".
 */
export interface HeroActionLink {
  type?: ('reference' | 'custom') | null;
  newTab?: boolean | null;
  reference?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  /**
   * Add protocol (http:// or https://) if the link is external
   */
  url?: string | null;
  label: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillListBlock".
 */
export interface PillListBlock {
  /**
   * Small uppercase label shown above the heading
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Short paragraph below the heading
   */
  intro?: string | null;
  /**
   * Background treatment
   */
  surface?: ('dark' | 'light') | null;
  items?:
    | {
        /**
         * e.g. "my-package"
         */
        label: string;
        /**
         * Optional external link
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pill-list';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostsBlock".
 */
export interface PostsBlock {
  title: string;
  description?: string | null;
  /**
   * Maximum number of posts to display
   */
  limit: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'posts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowcaseBlock".
 */
export interface ShowcaseBlock {
  /**
   * Small uppercase label shown above the heading
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Short paragraph below the heading
   */
  intro?: string | null;
  enableHeaderLink?: boolean | null;
  link?: ShowcaseHeaderLink;
  items?:
    | {
        /**
         * Small badge, e.g. "Platform"
         */
        tag?: string | null;
        title: string;
        description: string;
        /**
         * Monospace line, e.g. "Nx · Payload · Postgres"
         */
        meta?: string | null;
        link: ShowcaseItemLink;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'showcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowcaseHeaderLink".
 */
export interface ShowcaseHeaderLink {
  type?: ('reference' | 'custom') | null;
  newTab?: boolean | null;
  reference?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  /**
   * Add protocol (http:// or https://) if the link is external
   */
  url?: string | null;
  label: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShowcaseItemLink".
 */
export interface ShowcaseItemLink {
  type?: ('reference' | 'custom') | null;
  newTab?: boolean | null;
  reference?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  /**
   * Add protocol (http:// or https://) if the link is external
   */
  url?: string | null;
  label: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToursBlock".
 */
export interface ToursBlock {
  title: string;
  description?: string | null;
  /**
   * Maximum number of tours to display
   */
  limit: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tours';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  /**
   * Select a video.
   */
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * Questions and answers shown to all users in the admin help drawer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  _order?: string | null;
  question: string;
  /**
   * Plain text; line breaks are preserved.
   */
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Decide what appears in your website's menu and in what order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  tenant?: (number | null) | Tenant;
  items?: NavigationArrayItems;
  updatedAt: string;
  createdAt: string;
}
/**
 * Wineries, hotels and other places your tours visit. Add a place once and reuse it across tours.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * The name of the place, as it should appear in an itinerary.
   */
  name: string;
  /**
   * What sort of place this is. The list is curated by the platform.
   */
  kind: number | PlatformLabel;
  /**
   * Optional link to the place.
   */
  url?: string | null;
  /**
   * A short line about the place, shown next to it in the itinerary.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shared vocabularies used across all workspaces, such as the kinds a place can be. Editors pick from these; only system users maintain them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-labels".
 */
export interface PlatformLabel {
  id: number;
  /**
   * Which picker this label appears in.
   */
  type: 'place-kind' | 'stock-subject';
  /**
   * Short and lower case, e.g. "winery", "river valley". Must be unique within its type.
   */
  name: string;
  /**
   * Shown wherever the label appears. Pick a generic icon if none fits.
   */
  icon: string;
  /**
   * What this label is for and when to use it. Guidance for whoever maintains the list.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure the application name, landing page, and optional tenant brand mark.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  general: SiteSettingsGeneral;
  footer?: SiteSettingsFooter;
  tourSignups?: SiteSettingsTourSignups;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SiteSettingsGeneral".
 */
export interface SiteSettingsGeneral {
  appName: string;
  /**
   * The page that will be used as the landing page for the application.
   */
  landingPage: number | Page;
  /**
   * Optional tenant brand mark - use for a more unique identity.
   */
  icon?: {
    source?: ('svg' | 'upload') | null;
    /**
     * Paste raw SVG markup or generate a geometric icon. The viewBox attribute is required for correct scaling.
     */
    svgCode?: string | null;
    /**
     * Upload an image. Use the crop tool to select a 1:1 region.
     */
    file?: (number | null) | Media;
  };
  /**
   * The default locale for the client. Must be one of the supported locales for the workspace.
   */
  defaultLocale: 'en' | 'sv';
}
/**
 * Control what the site footer displays.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SiteSettingsFooter".
 */
export interface SiteSettingsFooter {
  /**
   * Uncheck to hide the footer on all pages.
   */
  enabled?: boolean | null;
  /**
   * Compact keeps everything on one centered row. Expanded gives the tagline, links and contacts their own columns.
   */
  variant?: ('compact' | 'standard' | 'expanded') | null;
  linkSource?: ('navigation' | 'custom' | 'none') | null;
  /**
   * Pick the pages worth a footer link — usually fewer than the top navigation.
   */
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          /**
           * Add protocol (http:// or https://) if the link is external
           */
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Short text above the footer links, e.g. a one-line description of the business.
   */
  tagline?: string | null;
  /**
   * Email, phone and social media to display in the footer.
   */
  contact?:
    | {
        platform:
          | 'discord'
          | 'email'
          | 'facebook'
          | 'github'
          | 'instagram'
          | 'linkedin'
          | 'npm'
          | 'phone'
          | 'web'
          | 'x'
          | 'youtube';
        email?: string | null;
        phone?: string | null;
        url?: string | null;
        withLabel?: boolean | null;
        /**
         * Short text to display next to the icon
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Uncheck to leave the copyright line out of the footer.
   */
  showCopyright?: boolean | null;
  /**
   * Use {year} for the current year. Defaults to "© {year} <application name>" when empty.
   */
  copyright?: string | null;
  /**
   * Display the running release, e.g. web@1.4.0+ab12cd3.
   */
  showVersion?: boolean | null;
}
/**
 * What customers are told when they sign up for a tour, and how long their details are kept.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SiteSettingsTourSignups".
 */
export interface SiteSettingsTourSignups {
  /**
   * Who gets an email when someone signs up for a tour. Leave empty to be told nothing.
   */
  notificationRecipients?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Linked from the signup form and the confirmation email. No page yet? Create a starter one below.
   */
  privacyPage?: (number | null) | Page;
  /**
   * When set, customers must accept these terms before they can sign up.
   */
  termsPage?: (number | null) | Page;
  /**
   * Names, emails and phone numbers are cleared this long after the tour departs. Party sizes and statuses are kept. This number is also what customers are told on the signup form.
   */
  retentionDays?: number | null;
}
/**
 * Shared images provided by the platform, free for any workspace to use. Upload your own photos under Media when you need a specific place.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-media".
 */
export interface StockMedia {
  id: number;
  /**
   * Alternative text for SEO and accessibility. Describe what the image shows.
   */
  alt: string;
  /**
   * What the image shows. The list is curated by the platform.
   */
  subject?: (number | null) | PlatformLabel;
  prefix?: string | null;
  /**
   * Photographer or source, where the licence requires attribution.
   */
  credit?: string | null;
  /**
   * The licence this image is used under, so its terms can be checked later.
   */
  licence?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    meta?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Customers who have signed up for a tour. The signup list also lives inside each tour, which is where you normally work with it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-signups".
 */
export interface TourSignup {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * The tour this signup is for.
   */
  tour: number | Tour;
  name: string;
  /**
   * How many people this signup is for. Capacity counts people, not signups.
   */
  people: number;
  email: string;
  /**
   * Optional, but worth having on the day of departure.
   */
  phone?: string | null;
  /**
   * Set when the customer signs up: booked while there is room, waiting list once the tour is full.
   */
  status: 'booked' | 'waiting' | 'cancelled';
  /**
   * Place in the waiting list. Reorder the queue from the tour instead of editing this.
   */
  queuePosition?: number | null;
  /**
   * Your own notes on this signup. Never shown to the customer.
   */
  notes?: string | null;
  statusChangedAt?: string | null;
  /**
   * When the customer accepted the terms, recorded by the server at signup.
   */
  termsAcceptedAt?: string | null;
  anonymizedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tours are the products you sell. Describe the trip, plan the days and publish when ready.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * The name of the tour, used in listings and navigation.
   */
  title: string;
  /**
   * Pick a shared image to set the mood, or upload your own photo of the actual places for an accurate one.
   */
  heroImage:
    | {
        relationTo: 'stock-media';
        value: number | StockMedia;
      }
    | {
        relationTo: 'media';
        value: number | Media;
      };
  /**
   * Short teaser shown on listing cards.
   */
  summary: string;
  /**
   * Where the tour takes place, e.g. "Tuscany, Italy".
   */
  destination: string;
  /**
   * How long the tour lasts, e.g. "7 days".
   */
  duration?: string | null;
  /**
   * Booking commits the customer and you invoice afterwards. Register interest is non-binding — use it when the departure is not confirmed yet.
   */
  intent: 'booking' | 'interest';
  /**
   * The day the tour departs. Leave empty while the date is unconfirmed.
   */
  departureDate?: string | null;
  /**
   * The last day customers can sign up. Optional.
   */
  bookingDeadline?: string | null;
  /**
   * Shown instead of a departure date, e.g. "Autumn 2027 — dates to be confirmed".
   */
  departureNote?: string | null;
  /**
   * Price per person, excluding currency.
   */
  price: number;
  currency: 'EUR' | 'SEK' | 'USD' | 'GBP';
  /**
   * How many people the tour has room for. Counts people, not signups — a signup for four takes four places. Leave empty for no limit.
   */
  maxCustomers?: number | null;
  /**
   * Stop taking new signups, including the waiting list. Signups already received are untouched.
   */
  signupsClosed?: boolean | null;
  /**
   * One line per thing the price covers.
   */
  included?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One line per thing customers pay for themselves.
   */
  notIncluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  itinerary?: TourItinerary;
  /**
   * Everything that does not fit the structure above: preamble, practical info.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Used for url paths. Will be automatically generated from title if left empty.
   */
  slug: string;
  seatsTaken?: number | null;
  seatsWaiting?: number | null;
  seatsLeft?: number | null;
  signupsFull?: boolean | null;
  signupsQueueOnly?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Messages visitors have sent through the forms on your website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  tenant?: (number | null) | Tenant;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'anonymize-tour-signups';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'anonymize-tour-signups') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'platform-labels';
        value: number | PlatformLabel;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'reusable-content';
        value: number | ReusableContent;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'stock-media';
        value: number | StockMedia;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'tour-signups';
        value: number | TourSignup;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'tenants';
        value: number | Tenant;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'tenants';
        value: number | Tenant;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  relations?:
    | T
    | {
        relatedPosts?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  _order?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  filenameWithoutPrefix?: T;
  alt?: T;
  caption?: T;
  tags?: T;
  prefix?: T;
  external?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        meta?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  tenant?: T;
  items?: T | NavigationArrayItemsSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavigationArrayItems_select".
 */
export interface NavigationArrayItemsSelect<T extends boolean = true> {
  reference?: T;
  labelSource?: T;
  customLabel?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  header?: T;
  layout?: T | {};
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  kind?: T;
  url?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-labels_select".
 */
export interface PlatformLabelsSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  icon?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  authors?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-content_select".
 */
export interface ReusableContentSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  layout?: T | {};
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  general?: T | SiteSettingsGeneralSelect<T>;
  footer?: T | SiteSettingsFooterSelect<T>;
  tourSignups?: T | SiteSettingsTourSignupsSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SiteSettingsGeneral_select".
 */
export interface SiteSettingsGeneralSelect<T extends boolean = true> {
  appName?: T;
  landingPage?: T;
  icon?:
    | T
    | {
        source?: T;
        svgCode?: T;
        file?: T;
      };
  defaultLocale?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SiteSettingsFooter_select".
 */
export interface SiteSettingsFooterSelect<T extends boolean = true> {
  enabled?: T;
  variant?: T;
  linkSource?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  tagline?: T;
  contact?:
    | T
    | {
        platform?: T;
        email?: T;
        phone?: T;
        url?: T;
        withLabel?: T;
        label?: T;
        id?: T;
      };
  showCopyright?: T;
  copyright?: T;
  showVersion?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SiteSettingsTourSignups_select".
 */
export interface SiteSettingsTourSignupsSelect<T extends boolean = true> {
  notificationRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  privacyPage?: T;
  termsPage?: T;
  retentionDays?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-media_select".
 */
export interface StockMediaSelect<T extends boolean = true> {
  alt?: T;
  subject?: T;
  prefix?: T;
  credit?: T;
  licence?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        meta?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  brand?:
    | T
    | {
        icon?: T;
        color?: T;
      };
  relations?:
    | T
    | {
        relatedMedia?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  iconConfig?: T;
  name?: T;
  description?: T;
  supportedLocales?: T;
  domains?:
    | T
    | {
        hostname?: T;
        app?: T;
        isPrimary?: T;
        certificate?:
          | T
          | {
              isConfigured?: T;
              isApex?: T;
              status?: T;
              checkedAt?: T;
              dnsValidationHostname?: T;
              dnsValidationTarget?: T;
              dnsValidationInstructions?: T;
              rateLimitedUntil?: T;
            };
        id?: T;
      };
  relations?:
    | T
    | {
        relatedUsers?: T;
        relatedPages?: T;
        relatedPosts?: T;
        relatedCategories?: T;
        relatedMedia?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-signups_select".
 */
export interface TourSignupsSelect<T extends boolean = true> {
  tenant?: T;
  tour?: T;
  name?: T;
  people?: T;
  email?: T;
  phone?: T;
  status?: T;
  queuePosition?: T;
  notes?: T;
  statusChangedAt?: T;
  termsAcceptedAt?: T;
  anonymizedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  heroImage?: T;
  summary?: T;
  destination?: T;
  duration?: T;
  intent?: T;
  departureDate?: T;
  bookingDeadline?: T;
  departureNote?: T;
  price?: T;
  currency?: T;
  maxCustomers?: T;
  signupsClosed?: T;
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  notIncluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  itinerary?: T | TourItinerarySelect<T>;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  seatsTaken?: T;
  seatsWaiting?: T;
  seatsLeft?: T;
  signupsFull?: T;
  signupsQueueOnly?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TourItinerary_select".
 */
export interface TourItinerarySelect<T extends boolean = true> {
  title?: T;
  places?: T;
  description?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenants?: T | TenantsArrayFieldSelect<T>;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TenantsArrayField_select".
 */
export interface TenantsArrayFieldSelect<T extends boolean = true> {
  tenant?: T;
  role?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              min?: T;
              max?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        date?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        radio?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskAnonymize-tour-signups".
 */
export interface TaskAnonymizeTourSignups {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
