# Only for Development.
# Should be started from workspace root.

# Hard coded environment variables is a valid workaround for using Postgres image locally.
# Should match what we get from `process.env.DATABASE_URL`.

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cms
    networks:
      - local
    volumes:
      - type: volume
        source: db_postgres
        target: /var/lib/postgresql/data

  cms:
    container_name: cms
    image: cms
    build:
      context: ../../
      dockerfile: apps/cms/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.docker
    networks:
      - local
    depends_on:
      - postgres

networks:
  local:
    name: payload-local
    driver: bridge

volumes:
  db_postgres:
    driver: local
