.DS_Store
.git
.github

# Config
.settings
.verdaccio
.vscode

# Nx
.nx
migrations.json
tools
*.log

# Temporary files
coverage
dist
node_modules
tmp

# Lock files
bun.lockb
package-lock.json
pnpm-lock.yaml
yarn.lock

# Apps
/apps/*
!/apps/cms

# Prevent overriding Infisical environment variables
.env.*
