# Only for Development.
# Should be started from workspace root.

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    env_file: .env.local
    networks:
      - local
    volumes:
      - type: volume
        source: db_postgres
        target: /var/lib/postgresql/data

  cms:
    container_name: cms
    image: cms
    build:
      context: ../../
      dockerfile: apps/cms/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.local
    environment:
      # Override the values different from .env
      - POSTGRES_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
    networks:
      - local
    depends_on:
      - postgres

networks:
  local:
    name: payload-local
    driver: bridge

volumes:
  db_postgres:
    driver: local
