import {
  type ThemeRecipe,
  type ThemeTokens,
  buildThemeTokens
} from './build-theme-tokens';

/** The three files a committed theme folder holds. */
export type ThemeFiles = {
  'tokens-light.css': string;
  'tokens-dark.css': string;
  'tailwind-base.css': string;
};

const block = (selector: string, tokens: ThemeTokens): string =>
  [
    `${selector} {`,
    ...Object.entries(tokens).map(([name, value]) => `  ${name}: ${value};`),
    '}',
    ''
  ].join('\n');

/**
 * Emit a theme as the files `theme-sync` reads.
 *
 * The counterpart to injecting a theme at runtime: dropped into
 * `libs/shared/theme/src/lib/<name>/` and added to `SITE_THEMES`, the same
 * recipe becomes a built-in that ships in the CSS bundle and goes through code
 * review.
 *
 * Palette colours are written as `var(--color-…)` here, unlike the runtime
 * form. These files are compiled, so the alias survives and says which palette
 * step was chosen — which a reviewer can judge and a literal oklch triple
 * cannot.
 *
 * `tokens-light.css` uses `:root` and `tokens-dark.css` uses `.dark`, never the
 * `[data-theme=dark]` attribute: once the attribute carries the theme name that
 * selector can no longer match, and `theme-sync` rejects a site theme written
 * that way.
 *
 * @param name - Folder and theme name, used in the header comment
 * @param recipe - The theme's recipe
 * @param overrides - Hand-edited tokens, applied last
 * @returns File contents keyed by filename
 */
export function themeFiles(
  name: string,
  recipe: ThemeRecipe,
  overrides: { light?: ThemeTokens; dark?: ThemeTokens } = {}
): ThemeFiles {
  const { light, dark } = buildThemeTokens(recipe, overrides, 'alias');

  return {
    'tokens-light.css': block(':root', light),
    'tokens-dark.css': block('.dark', dark),
    'tailwind-base.css': [
      `/* ${name} theme — generated by the theme studio */`,
      "@import './tokens-light.css';",
      "@import './tokens-dark.css';",
      '',
      '/* Core setup — variants, theme mappings, base layer */',
      "@import '../_core/tailwind-setup.css';",
      ''
    ].join('\n')
  };
}
