/* AUTO-GENERATED — do not edit manually. Run `pnpm nx sync` to update. */

/** One built-in theme's declarations, per colour scheme. */
export type BuiltInThemeTokens = {
  light: Record<string, string>;
  dark: Record<string, string>;
};

export const BUILT_IN_TOKENS: Record<string, BuiltInThemeTokens> = {
  shadcn: {
    light: {
      '--brand-50': 'var(--color-zinc-50)',
      '--brand-100': 'var(--color-zinc-100)',
      '--brand-200': 'var(--color-zinc-200)',
      '--brand-300': 'var(--color-zinc-300)',
      '--brand-400': 'var(--color-zinc-400)',
      '--brand-500': 'var(--color-zinc-500)',
      '--brand-600': 'var(--color-zinc-600)',
      '--brand-700': 'var(--color-zinc-700)',
      '--brand-800': 'var(--color-zinc-800)',
      '--brand-900': 'var(--color-zinc-900)',
      '--brand-950': 'var(--color-zinc-950)',
      '--radius': '0.625rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'oklch(1 0 0)',
      '--foreground': 'oklch(0.145 0 0)',
      '--card': 'oklch(1 0 0)',
      '--card-foreground': 'oklch(0.145 0 0)',
      '--popover': 'oklch(1 0 0)',
      '--popover-foreground': 'oklch(0.145 0 0)',
      '--primary': 'oklch(0.205 0 0)',
      '--primary-foreground': 'oklch(0.985 0 0)',
      '--secondary': 'oklch(0.97 0 0)',
      '--secondary-foreground': 'oklch(0.205 0 0)',
      '--muted': 'oklch(0.97 0 0)',
      '--muted-foreground': 'oklch(0.536 0 0)',
      '--accent': 'oklch(0.97 0 0)',
      '--accent-foreground': 'oklch(0.205 0 0)',
      '--destructive': 'oklch(0.577 0.245 27.325)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--border': 'oklch(0.922 0 0)',
      '--input': 'oklch(0.922 0 0)',
      '--ring': 'oklch(0.708 0 0)',
      '--chart-1': 'oklch(0.87 0 0)',
      '--chart-2': 'oklch(0.556 0 0)',
      '--chart-3': 'oklch(0.439 0 0)',
      '--chart-4': 'oklch(0.371 0 0)',
      '--chart-5': 'oklch(0.269 0 0)',
      '--sidebar': 'oklch(0.985 0 0)',
      '--sidebar-foreground': 'oklch(0.145 0 0)',
      '--sidebar-primary': 'oklch(0.205 0 0)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.97 0 0)',
      '--sidebar-accent-foreground': 'oklch(0.205 0 0)',
      '--sidebar-border': 'oklch(0.922 0 0)',
      '--sidebar-ring': 'oklch(0.708 0 0)',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-link': 'var(--primary)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-surface-invert': 'oklch(0.205 0 0)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--primary)',
      '--links-hover': 'var(--primary)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--primary)',
      '--underline-hover': 'var(--primary)'
    },
    dark: {
      '--background': 'oklch(0.145 0 0)',
      '--foreground': 'oklch(0.985 0 0)',
      '--card': 'oklch(0.205 0 0)',
      '--card-foreground': 'oklch(0.985 0 0)',
      '--popover': 'oklch(0.205 0 0)',
      '--popover-foreground': 'oklch(0.985 0 0)',
      '--primary': 'oklch(0.922 0 0)',
      '--primary-foreground': 'oklch(0.205 0 0)',
      '--secondary': 'oklch(0.269 0 0)',
      '--secondary-foreground': 'oklch(0.985 0 0)',
      '--muted': 'oklch(0.269 0 0)',
      '--muted-foreground': 'oklch(0.708 0 0)',
      '--accent': 'oklch(0.269 0 0)',
      '--accent-foreground': 'oklch(0.985 0 0)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--ring': 'oklch(0.556 0 0)',
      '--chart-1': 'oklch(0.87 0 0)',
      '--chart-2': 'oklch(0.556 0 0)',
      '--chart-3': 'oklch(0.439 0 0)',
      '--chart-4': 'oklch(0.371 0 0)',
      '--chart-5': 'oklch(0.269 0 0)',
      '--sidebar': 'oklch(0.205 0 0)',
      '--sidebar-foreground': 'oklch(0.985 0 0)',
      '--sidebar-primary': 'oklch(0.488 0.243 264.376)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.269 0 0)',
      '--sidebar-accent-foreground': 'oklch(0.985 0 0)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--sidebar-ring': 'oklch(0.556 0 0)',
      '--core-surface-invert': 'var(--card)'
    }
  },
  'payload-admin': {
    light: {
      '--brand-50': '#eef5fb',
      '--brand-100': '#d6e8f4',
      '--brand-200': '#b3d1e9',
      '--brand-300': '#85aed1',
      '--brand-400': '#588bae',
      '--brand-500': '#2f6ba1',
      '--brand-600': '#0e4d92',
      '--brand-700': '#0d3f76',
      '--brand-800': '#0c325e',
      '--brand-900': '#0a2347',
      '--brand-950': '#081830',
      '--radius': '0.625rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'oklch(1 0 0)',
      '--foreground': 'oklch(0.141 0.005 285.823)',
      '--card': 'oklch(1 0 0)',
      '--card-foreground': 'oklch(0.141 0.005 285.823)',
      '--popover': 'oklch(1 0 0)',
      '--popover-foreground': 'oklch(0.141 0.005 285.823)',
      '--primary': 'oklch(0.21 0.006 285.885)',
      '--primary-foreground': 'oklch(0.985 0 0)',
      '--secondary': 'oklch(0.967 0.001 286.375)',
      '--secondary-foreground': 'oklch(0.21 0.006 285.885)',
      '--muted': 'oklch(0.967 0.001 286.375)',
      '--muted-foreground': 'oklch(0.536 0.016 285.938)',
      '--accent': 'oklch(0.967 0.001 286.375)',
      '--accent-foreground': 'oklch(0.21 0.006 285.885)',
      '--destructive': 'oklch(0.577 0.245 27.325)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--border': 'oklch(0.92 0.004 286.32)',
      '--input': 'oklch(0.92 0.004 286.32)',
      '--ring': 'oklch(0.705 0.015 286.067)',
      '--chart-1': 'oklch(0.646 0.222 41.116)',
      '--chart-2': 'oklch(0.6 0.118 184.704)',
      '--chart-3': 'oklch(0.398 0.07 227.392)',
      '--chart-4': 'oklch(0.828 0.189 84.429)',
      '--chart-5': 'oklch(0.769 0.188 70.08)',
      '--sidebar': 'oklch(0.985 0 0)',
      '--sidebar-foreground': 'oklch(0.141 0.005 285.823)',
      '--sidebar-primary': 'oklch(0.21 0.006 285.885)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.967 0.001 286.375)',
      '--sidebar-accent-foreground': 'oklch(0.21 0.006 285.885)',
      '--sidebar-border': 'oklch(0.92 0.004 286.32)',
      '--sidebar-ring': 'oklch(0.705 0.015 286.067)',
      '--link': 'var(--brand-600)',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-link': 'var(--link)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-surface-invert': 'var(--primary)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--primary)',
      '--links-hover': 'var(--primary)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--primary)',
      '--underline-hover': 'var(--primary)'
    },
    dark: {
      '--background': 'oklch(0.141 0.005 285.823)',
      '--foreground': 'oklch(0.985 0 0)',
      '--card': 'oklch(0.21 0.006 285.885)',
      '--card-foreground': 'oklch(0.985 0 0)',
      '--popover': 'oklch(0.21 0.006 285.885)',
      '--popover-foreground': 'oklch(0.985 0 0)',
      '--primary': 'oklch(0.92 0.004 286.32)',
      '--primary-foreground': 'oklch(0.21 0.006 285.885)',
      '--secondary': 'oklch(0.274 0.006 286.033)',
      '--secondary-foreground': 'oklch(0.985 0 0)',
      '--muted': 'oklch(0.274 0.006 286.033)',
      '--muted-foreground': 'oklch(0.705 0.015 286.067)',
      '--accent': 'oklch(0.274 0.006 286.033)',
      '--accent-foreground': 'oklch(0.985 0 0)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--ring': 'oklch(0.552 0.016 285.938)',
      '--chart-1': 'oklch(0.488 0.243 264.376)',
      '--chart-2': 'oklch(0.696 0.17 162.48)',
      '--chart-3': 'oklch(0.769 0.188 70.08)',
      '--chart-4': 'oklch(0.627 0.265 303.9)',
      '--chart-5': 'oklch(0.645 0.246 16.439)',
      '--sidebar': 'oklch(0.21 0.006 285.885)',
      '--sidebar-foreground': 'oklch(0.985 0 0)',
      '--sidebar-primary': 'oklch(0.488 0.243 264.376)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.274 0.006 286.033)',
      '--sidebar-accent-foreground': 'oklch(0.985 0 0)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--sidebar-ring': 'oklch(0.552 0.016 285.938)',
      '--link': 'var(--brand-300)',
      '--core-link': 'var(--link)',
      '--core-surface-invert': 'var(--card)'
    }
  },
  spotlight: {
    light: {
      '--brand-50': 'var(--color-teal-50)',
      '--brand-100': 'var(--color-teal-100)',
      '--brand-200': 'var(--color-teal-200)',
      '--brand-300': 'var(--color-teal-300)',
      '--brand-400': 'var(--color-teal-400)',
      '--brand-500': 'var(--color-teal-500)',
      '--brand-600': 'var(--color-teal-600)',
      '--brand-700': 'var(--color-teal-700)',
      '--brand-800': 'var(--color-teal-800)',
      '--brand-900': 'var(--color-teal-900)',
      '--brand-950': 'var(--color-teal-950)',
      '--core-action-btn-foreground': 'var(--color-zinc-600)',
      '--core-action-btn-foreground-hover': 'var(--color-teal-700)',
      '--core-action-btn-background': "theme('colors.white / 0.9')",
      '--core-action-btn-border': "theme('colors.zinc.900 / 0.05')",
      '--core-action-btn-border-hover': "theme('colors.zinc.900 / 0.1')",
      '--core-action-btn-icon-fill': 'var(--color-zinc-100)',
      '--core-action-btn-shadow': "theme('colors.zinc.800 / 0.05')",
      '--core-background-body': 'var(--color-zinc-50)',
      '--core-background-content': 'var(--color-white)',
      '--core-content-border': 'var(--color-zinc-100)',
      '--core-headline': 'var(--color-zinc-800)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-header': 'var(--color-zinc-900)',
      '--core-link': 'var(--color-teal-700)',
      '--core-navbar': "theme('colors.white / 0.9')",
      '--core-navbar-border': "theme('colors.zinc.900 / 0.05')",
      '--core-navbar-shadow': "theme('colors.zinc.800 / 0.05')",
      '--core-nav-link': 'var(--color-zinc-800)',
      '--core-nav-link-active': 'var(--color-teal-700)',
      '--core-nav-link-hover': 'var(--color-teal-700)',
      '--core-surface-invert': 'var(--color-zinc-900)',
      '--core-text': 'var(--color-zinc-600)',
      '--radius': '0.5rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'var(--core-background-content)',
      '--foreground': 'var(--core-text)',
      '--card': 'var(--color-zinc-50)',
      '--card-foreground': 'var(--color-zinc-600)',
      '--popover': 'var(--color-zinc-50)',
      '--popover-foreground': 'var(--color-zinc-900)',
      '--primary': 'var(--color-zinc-900)',
      '--primary-foreground': 'var(--color-zinc-50)',
      '--secondary': 'var(--color-zinc-100)',
      '--secondary-foreground': 'var(--color-zinc-900)',
      '--muted': 'var(--color-zinc-100)',
      '--muted-foreground': 'var(--color-zinc-600)',
      '--accent': 'var(--color-zinc-100)',
      '--accent-foreground': 'var(--color-zinc-900)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--border': 'var(--color-zinc-100)',
      '--input': 'var(--color-zinc-300)',
      '--ring': 'var(--color-zinc-900)',
      '--chart-1': 'oklch(0.646 0.222 41.116)',
      '--chart-2': 'oklch(0.6 0.118 184.704)',
      '--chart-3': 'oklch(0.398 0.07 227.392)',
      '--chart-4': 'oklch(0.828 0.189 84.429)',
      '--chart-5': 'oklch(0.769 0.188 70.08)',
      '--sidebar': 'oklch(0.985 0 0)',
      '--sidebar-foreground': 'oklch(0.141 0.005 285.823)',
      '--sidebar-primary': 'oklch(0.21 0.006 285.885)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.967 0.001 286.375)',
      '--sidebar-accent-foreground': 'oklch(0.21 0.006 285.885)',
      '--sidebar-border': 'oklch(0.92 0.004 286.32)',
      '--sidebar-ring': 'oklch(0.705 0.015 286.067)',
      '--body': 'var(--core-text)',
      '--bold': 'var(--primary)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--color-zinc-500)',
      '--code': 'var(--color-zinc-700)',
      '--code-bg': "theme('colors.zinc.300 / 0.2')",
      '--counters': 'var(--primary)',
      '--headings': 'var(--core-header)',
      '--hr': 'var(--color-zinc-300)',
      '--links': 'var(--brand-600)',
      '--links-hover': 'var(--brand-600)',
      '--pre-bg': 'var(--color-zinc-900)',
      '--pre-border': 'transparent',
      '--pre-code': 'var(--secondary)',
      '--quote-borders': 'var(--color-zinc-200)',
      '--td-borders': 'var(--secondary)',
      '--th-borders': 'var(--color-zinc-200)',
      '--underline': "theme('colors.teal.500 / 0.2')",
      '--underline-hover': 'var(--brand-500)'
    },
    dark: {
      '--core-action-btn-foreground': 'var(--color-zinc-400)',
      '--core-action-btn-foreground-hover': 'var(--color-teal-400)',
      '--core-action-btn-background': "theme('colors.zinc.800 / 0.9')",
      '--core-action-btn-border': "theme('colors.white / 0.1')",
      '--core-action-btn-border-hover': "theme('colors.white / 0.2')",
      '--core-action-btn-icon-fill': 'var(--color-zinc-700)',
      '--core-action-btn-shadow': "theme('colors.zinc.800 / 0.05')",
      '--core-background-body': 'var(--color-black)',
      '--core-background-content': 'var(--color-zinc-900)',
      '--core-content-border': "theme('colors.zinc.300 / 0.2')",
      '--core-header': 'var(--color-zinc-200)',
      '--core-headline': 'var(--color-zinc-100)',
      '--core-link': 'var(--color-teal-400)',
      '--core-navbar': "theme('colors.zinc.800 / 0.9')",
      '--core-navbar-border': "theme('colors.white / 0.10')",
      '--core-navbar-shadow': "theme('colors.zinc.800 / 0.05')",
      '--core-nav-link': 'var(--color-zinc-200)',
      '--core-nav-link-active': 'var(--color-teal-400)',
      '--core-nav-link-hover': 'var(--color-teal-400)',
      '--core-surface-invert': 'var(--color-zinc-700)',
      '--core-text': 'var(--color-zinc-400)',
      '--background': 'var(--core-background-content)',
      '--foreground': 'var(--core-text)',
      '--card': "theme('colors.zinc.800 / 0.5')",
      '--card-foreground': 'var(--color-zinc-400)',
      '--popover': 'var(--secondary)',
      '--popover-foreground': 'var(--secondary-foreground)',
      '--primary': 'var(--color-zinc-100)',
      '--primary-foreground': 'var(--color-zinc-900)',
      '--secondary': 'var(--color-zinc-800)',
      '--secondary-foreground': 'var(--color-zinc-100)',
      '--muted': 'var(--color-zinc-800)',
      '--muted-foreground': 'var(--color-zinc-400)',
      '--accent': 'var(--color-zinc-800)',
      '--accent-foreground': 'var(--color-zinc-100)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--border': "theme('colors.zinc.700 / 0.4')",
      '--input': "theme('colors.zinc.700 / 0.4')",
      '--ring': 'var(--primary)',
      '--chart-1': 'oklch(0.488 0.243 264.376)',
      '--chart-2': 'oklch(0.696 0.17 162.48)',
      '--chart-3': 'oklch(0.769 0.188 70.08)',
      '--chart-4': 'oklch(0.627 0.265 303.9)',
      '--chart-5': 'oklch(0.645 0.246 16.439)',
      '--sidebar': 'oklch(0.21 0.006 285.885)',
      '--sidebar-foreground': 'oklch(0.985 0 0)',
      '--sidebar-primary': 'oklch(0.488 0.243 264.376)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.274 0.006 286.033)',
      '--sidebar-accent-foreground': 'oklch(0.985 0 0)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--sidebar-ring': 'oklch(0.552 0.016 285.938)',
      '--body': 'var(--core-text)',
      '--bold': 'var(--color-zinc-200)',
      '--bullets': 'var(--color-zinc-200)',
      '--captions': 'var(--color-zinc-400)',
      '--code': 'var(--color-zinc-300)',
      '--code-bg': "theme('color.zinc.200 / 0.05')",
      '--counters': 'var(--color-zinc-200)',
      '--headings': 'var(--core-header)',
      '--hr': "theme('colors.zinc.600 / 0.4')",
      '--links': 'var(--color-teal-400)',
      '--links-hover': 'var(--color-teal-400)',
      '--pre-bg': 'rgb(0 0 0 / 0.4)',
      '--pre-border': "theme('colors.zinc.200 / 0.1')",
      '--pre-code': 'var(--color-zinc-100)',
      '--quote-borders': 'var(--color-zinc-500)',
      '--td-borders': 'var(--color-zinc-800)',
      '--th-borders': 'var(--color-zinc-700)',
      '--underline': "theme('colors.teal.400 / 0.3')",
      '--underline-hover': 'var(--color-teal-400)'
    }
  },
  'spotlight-fork': {
    light: {
      '--brand-50': 'var(--color-teal-50)',
      '--brand-100': 'var(--color-teal-100)',
      '--brand-200': 'var(--color-teal-200)',
      '--brand-300': 'var(--color-teal-300)',
      '--brand-400': 'var(--color-teal-400)',
      '--brand-500': 'var(--color-teal-500)',
      '--brand-600': 'var(--color-teal-600)',
      '--brand-700': 'var(--color-teal-700)',
      '--brand-800': 'var(--color-teal-800)',
      '--brand-900': 'var(--color-teal-900)',
      '--brand-950': 'var(--color-teal-950)',
      '--radius': '0.5rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'var(--color-white)',
      '--foreground': 'var(--core-text)',
      '--card': 'var(--color-zinc-50)',
      '--card-foreground': 'var(--color-zinc-600)',
      '--popover': 'var(--color-zinc-50)',
      '--popover-foreground': 'var(--color-zinc-900)',
      '--secondary': 'var(--color-zinc-100)',
      '--secondary-foreground': 'var(--color-zinc-900)',
      '--muted': 'var(--color-zinc-100)',
      '--muted-foreground': 'var(--color-zinc-600)',
      '--accent': 'var(--color-zinc-100)',
      '--accent-foreground': 'var(--color-zinc-900)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'var(--color-zinc-100)',
      '--input': 'var(--color-zinc-300)',
      '--sidebar': 'var(--color-zinc-50)',
      '--sidebar-foreground': 'var(--color-zinc-950)',
      '--sidebar-accent': 'var(--color-zinc-100)',
      '--sidebar-accent-foreground': 'var(--color-zinc-900)',
      '--sidebar-border': 'var(--color-zinc-200)',
      '--primary': 'var(--color-zinc-900)',
      '--primary-foreground': 'var(--color-zinc-50)',
      '--ring': 'var(--color-zinc-900)',
      '--sidebar-primary': 'var(--color-zinc-900)',
      '--sidebar-primary-foreground': 'var(--color-zinc-50)',
      '--sidebar-ring': 'var(--color-zinc-400)',
      '--chart-1': 'var(--color-orange-600)',
      '--chart-2': 'var(--color-teal-600)',
      '--chart-3': 'var(--color-cyan-900)',
      '--chart-4': 'var(--color-amber-400)',
      '--chart-5': 'var(--color-amber-500)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--color-teal-700)',
      '--core-action-btn-background': 'oklch(1 0 0 / 90%)',
      '--core-action-btn-border': 'oklch(0.21 0.006 285.885 / 5%)',
      '--core-action-btn-border-hover': 'oklch(0.21 0.006 285.885 / 10%)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'oklch(0.274 0.006 286.033 / 5%)',
      '--core-header': 'var(--color-zinc-900)',
      '--core-headline': 'var(--color-zinc-800)',
      '--core-navbar': 'oklch(1 0 0 / 90%)',
      '--core-navbar-border': 'oklch(0.21 0.006 285.885 / 5%)',
      '--core-navbar-shadow': 'oklch(0.274 0.006 286.033 / 5%)',
      '--core-nav-link': 'var(--color-zinc-800)',
      '--core-nav-link-active': 'var(--color-teal-700)',
      '--core-nav-link-hover': 'var(--color-teal-700)',
      '--core-text': 'var(--color-zinc-600)',
      '--body': 'var(--core-text)',
      '--bold': 'var(--primary)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--color-zinc-500)',
      '--code': 'var(--color-zinc-700)',
      '--code-bg': 'oklch(0.871 0.006 286.286 / 20%)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--core-header)',
      '--hr': 'var(--color-zinc-300)',
      '--links': 'var(--brand-600)',
      '--links-hover': 'var(--brand-600)',
      '--pre-bg': 'var(--color-zinc-900)',
      '--pre-border': 'transparent',
      '--pre-code': 'var(--secondary)',
      '--quote-borders': 'var(--color-zinc-200)',
      '--td-borders': 'var(--secondary)',
      '--th-borders': 'var(--color-zinc-200)',
      '--underline': 'oklch(0.704 0.14 182.503 / 20%)',
      '--underline-hover': 'var(--brand-500)',
      '--core-background-body': 'var(--color-zinc-50)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--color-zinc-100)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-link': 'var(--brand-700)',
      '--core-surface-invert': 'var(--color-zinc-900)'
    },
    dark: {
      '--background': 'var(--core-background-content)',
      '--foreground': 'var(--core-text)',
      '--card': 'oklch(0.274 0.006 286.033 / 50%)',
      '--card-foreground': 'var(--color-zinc-400)',
      '--popover': 'var(--secondary)',
      '--popover-foreground': 'var(--secondary-foreground)',
      '--secondary': 'var(--color-zinc-800)',
      '--secondary-foreground': 'var(--color-zinc-100)',
      '--muted': 'var(--color-zinc-800)',
      '--muted-foreground': 'var(--color-zinc-400)',
      '--accent': 'var(--color-zinc-800)',
      '--accent-foreground': 'var(--color-zinc-100)',
      '--destructive': 'var(--color-red-600)',
      '--destructive-foreground': 'var(--color-white)',
      '--border': 'oklch(0.37 0.013 285.805 / 40%)',
      '--input': 'oklch(0.37 0.013 285.805 / 40%)',
      '--sidebar': 'var(--color-zinc-900)',
      '--sidebar-foreground': 'var(--color-zinc-50)',
      '--sidebar-accent': 'var(--color-zinc-800)',
      '--sidebar-accent-foreground': 'var(--color-zinc-50)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--primary': 'var(--color-zinc-100)',
      '--primary-foreground': 'var(--color-zinc-900)',
      '--ring': 'var(--primary)',
      '--sidebar-primary': 'oklch(0.488 0.243 264.376)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-ring': 'var(--color-zinc-500)',
      '--chart-1': 'var(--color-blue-700)',
      '--chart-2': 'var(--color-emerald-500)',
      '--chart-3': 'var(--color-amber-500)',
      '--chart-4': 'var(--color-purple-500)',
      '--chart-5': 'var(--color-rose-500)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--core-background-body': 'var(--color-black)',
      '--core-background-content': 'var(--color-zinc-900)',
      '--core-content-border': 'oklch(0.871 0.006 286.286 / 20%)',
      '--core-link': 'var(--brand-400)',
      '--core-surface-invert': 'var(--color-zinc-700)',
      '--core-action-btn-foreground-hover': 'var(--color-teal-400)',
      '--core-action-btn-background': 'oklch(0.274 0.006 286.033 / 90%)',
      '--core-action-btn-border': 'oklch(1 0 0 / 10%)',
      '--core-action-btn-border-hover': 'oklch(1 0 0 / 20%)',
      '--core-action-btn-icon-fill': 'var(--color-zinc-700)',
      '--core-action-btn-shadow': 'oklch(0.274 0.006 286.033 / 5%)',
      '--core-header': 'var(--color-zinc-200)',
      '--core-headline': 'var(--color-zinc-100)',
      '--core-navbar': 'oklch(0.274 0.006 286.033 / 90%)',
      '--core-navbar-border': 'oklch(1 0 0 / 10%)',
      '--core-navbar-shadow': 'oklch(0.274 0.006 286.033 / 5%)',
      '--core-nav-link': 'var(--color-zinc-200)',
      '--core-nav-link-active': 'var(--color-teal-400)',
      '--core-nav-link-hover': 'var(--color-teal-400)',
      '--core-text': 'var(--color-zinc-400)',
      '--body': 'var(--core-text)',
      '--bold': 'var(--color-zinc-200)',
      '--code': 'var(--color-zinc-300)',
      '--code-bg': 'oklch(0.92 0.004 286.32 / 5%)',
      '--headings': 'var(--core-header)',
      '--hr': 'oklch(0.442 0.017 285.786 / 40%)',
      '--pre-bg': 'rgb(0 0 0 / 0.4)',
      '--pre-border': 'oklch(0.92 0.004 286.32 / 10%)',
      '--pre-code': 'var(--color-zinc-100)',
      '--quote-borders': 'var(--color-zinc-500)',
      '--td-borders': 'var(--color-zinc-800)',
      '--th-borders': 'var(--color-zinc-700)',
      '--underline': 'oklch(0.777 0.152 181.912 / 30%)',
      '--bullets': 'var(--color-zinc-200)',
      '--captions': 'var(--color-zinc-400)',
      '--counters': 'var(--color-zinc-200)',
      '--links': 'var(--color-teal-400)',
      '--links-hover': 'var(--color-teal-400)',
      '--underline-hover': 'var(--color-teal-400)'
    }
  },
  codeware: {
    light: {
      '--steel-blue': '#588bae',
      '--yale-blue': '#0e4d92',
      '--space-cadet': '#1d2951',
      '--light-gray': '#d0d2d3',
      '--eerie-black': '#242526',
      '--darker-black': '#111111',
      '--brand-50': 'var(--color-blue-50)',
      '--brand-100': 'var(--color-blue-100)',
      '--brand-200': 'var(--color-blue-200)',
      '--brand-300': 'var(--color-blue-300)',
      '--brand-400': 'var(--color-blue-400)',
      '--brand-500': 'var(--color-blue-500)',
      '--brand-600': 'var(--color-blue-600)',
      '--brand-700': 'var(--color-blue-700)',
      '--brand-800': 'var(--color-blue-800)',
      '--brand-900': 'var(--color-blue-900)',
      '--brand-950': 'var(--color-blue-950)',
      '--radius': '0.625rem',
      '--radius-md': 'calc(var(--radius) - 0.125rem)',
      '--background': 'oklch(1 0 0)',
      '--foreground': 'oklch(0.141 0.005 285.823)',
      '--card': 'oklch(1 0 0)',
      '--card-foreground': 'oklch(0.141 0.005 285.823)',
      '--popover': 'oklch(1 0 0)',
      '--popover-foreground': 'oklch(0.141 0.005 285.823)',
      '--primary': 'oklch(0.21 0.006 285.885)',
      '--primary-foreground': 'oklch(0.985 0 0)',
      '--secondary': 'oklch(0.967 0.001 286.375)',
      '--secondary-foreground': 'oklch(0.21 0.006 285.885)',
      '--muted': 'oklch(0.967 0.001 286.375)',
      '--muted-foreground': 'oklch(0.536 0.016 285.938)',
      '--accent': 'oklch(0.967 0.001 286.375)',
      '--accent-foreground': 'oklch(0.21 0.006 285.885)',
      '--destructive': 'oklch(0.577 0.245 27.325)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-700)',
      '--success-subtle': 'var(--color-green-700)',
      '--warning-subtle': 'var(--color-amber-700)',
      '--border': 'oklch(0.92 0.004 286.32)',
      '--input': 'oklch(0.92 0.004 286.32)',
      '--ring': 'oklch(0.705 0.015 286.067)',
      '--chart-1': 'oklch(0.646 0.222 41.116)',
      '--chart-2': 'oklch(0.6 0.118 184.704)',
      '--chart-3': 'oklch(0.398 0.07 227.392)',
      '--chart-4': 'oklch(0.828 0.189 84.429)',
      '--chart-5': 'oklch(0.769 0.188 70.08)',
      '--sidebar': 'oklch(0.985 0 0)',
      '--sidebar-foreground': 'oklch(0.141 0.005 285.823)',
      '--sidebar-primary': 'oklch(0.21 0.006 285.885)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.967 0.001 286.375)',
      '--sidebar-accent-foreground': 'oklch(0.21 0.006 285.885)',
      '--sidebar-border': 'oklch(0.92 0.004 286.32)',
      '--sidebar-ring': 'oklch(0.705 0.015 286.067)',
      '--core-action-btn-foreground': 'var(--muted-foreground)',
      '--core-action-btn-foreground-hover': 'var(--foreground)',
      '--core-action-btn-background': 'var(--background)',
      '--core-action-btn-border': 'var(--border)',
      '--core-action-btn-border-hover': 'var(--border)',
      '--core-action-btn-icon-fill': 'var(--muted)',
      '--core-action-btn-shadow': 'transparent',
      '--core-background-body': 'var(--background)',
      '--core-background-content': 'var(--background)',
      '--core-content-border': 'var(--border)',
      '--core-font-body': 'Inter Variable, Inter, sans-serif',
      '--core-font-heading': 'Inter Variable, Inter, sans-serif',
      '--core-font-mono':
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
      '--core-header': 'var(--foreground)',
      '--core-headline': 'var(--foreground)',
      '--core-link': 'var(--brand-600)',
      '--core-surface-invert': 'var(--eerie-black)',
      '--core-navbar': 'var(--background)',
      '--core-navbar-border': 'var(--border)',
      '--core-navbar-shadow': 'transparent',
      '--core-nav-link': 'var(--foreground)',
      '--core-nav-link-active': 'var(--primary)',
      '--core-nav-link-hover': 'var(--primary)',
      '--core-text': 'var(--foreground)',
      '--body': 'var(--foreground)',
      '--bold': 'var(--foreground)',
      '--bullets': 'var(--primary)',
      '--captions': 'var(--muted-foreground)',
      '--code': 'var(--foreground)',
      '--code-bg': 'var(--muted)',
      '--counters': 'var(--primary)',
      '--headings': 'var(--foreground)',
      '--hr': 'var(--border)',
      '--links': 'var(--primary)',
      '--links-hover': 'var(--primary)',
      '--pre-bg': 'var(--secondary)',
      '--pre-border': 'var(--border)',
      '--pre-code': 'var(--foreground)',
      '--quote-borders': 'var(--border)',
      '--td-borders': 'var(--border)',
      '--th-borders': 'var(--border)',
      '--underline': 'var(--primary)',
      '--underline-hover': 'var(--primary)'
    },
    dark: {
      '--background': 'oklch(0.141 0.005 285.823)',
      '--foreground': 'oklch(0.985 0 0)',
      '--card': 'oklch(0.21 0.006 285.885)',
      '--card-foreground': 'oklch(0.985 0 0)',
      '--popover': 'oklch(0.21 0.006 285.885)',
      '--popover-foreground': 'oklch(0.985 0 0)',
      '--primary': 'oklch(0.92 0.004 286.32)',
      '--primary-foreground': 'oklch(0.21 0.006 285.885)',
      '--secondary': 'oklch(0.274 0.006 286.033)',
      '--secondary-foreground': 'oklch(0.985 0 0)',
      '--muted': 'oklch(0.274 0.006 286.033)',
      '--muted-foreground': 'oklch(0.705 0.015 286.067)',
      '--accent': 'oklch(0.274 0.006 286.033)',
      '--accent-foreground': 'oklch(0.985 0 0)',
      '--destructive': 'var(--color-red-700)',
      '--destructive-foreground': 'oklch(1 0 0)',
      '--destructive-subtle': 'var(--color-red-400)',
      '--success-subtle': 'var(--color-green-400)',
      '--warning-subtle': 'var(--color-amber-400)',
      '--border': 'oklch(1 0 0 / 10%)',
      '--input': 'oklch(1 0 0 / 15%)',
      '--ring': 'oklch(0.552 0.016 285.938)',
      '--chart-1': 'oklch(0.488 0.243 264.376)',
      '--chart-2': 'oklch(0.696 0.17 162.48)',
      '--chart-3': 'oklch(0.769 0.188 70.08)',
      '--chart-4': 'oklch(0.627 0.265 303.9)',
      '--chart-5': 'oklch(0.645 0.246 16.439)',
      '--sidebar': 'oklch(0.21 0.006 285.885)',
      '--sidebar-foreground': 'oklch(0.985 0 0)',
      '--sidebar-primary': 'oklch(0.488 0.243 264.376)',
      '--sidebar-primary-foreground': 'oklch(0.985 0 0)',
      '--sidebar-accent': 'oklch(0.274 0.006 286.033)',
      '--sidebar-accent-foreground': 'oklch(0.985 0 0)',
      '--sidebar-border': 'oklch(1 0 0 / 10%)',
      '--sidebar-ring': 'oklch(0.552 0.016 285.938)',
      '--core-link': 'var(--brand-400)',
      '--core-surface-invert': 'var(--card)'
    }
  }
};
